apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-241024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-241024 
  name: spring-241024
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spring-241024 
